### ISSUE TITLE
compiling issues

### ISSUE THREAD

**Issue by valpoder** [daniel-thompson/multistomp#1]
hello:

Im very interested in your code , but im having some issues compiling it...
What is the toolchain and OS ??
im using https://launchpad.net/gcc-arm-embedded  under windowns 7 64bits ( cygwin )

question : does the code works ??? :)

this is what im getting ...
---------------------------------------------------------------

$ git clone https://github.com/daniel-thompson/multistomp.git
Cloning into 'multistomp'...
remote: Counting objects: 70, done.
remote: Total 70 (delta 0), reused 0 (delta 0), pack-reused 70
Unpacking objects: 100% (70/70), done.

$ make
######## ERROR ########
        libopencm3 is not initialized.
        Please run:
        $ git submodule init
        $ git submodule update
        before running make.
######## ERROR ########
make: *** [Makefile:56: libopencm3] Error 1

$ git submodule init
Submodule 'libopencm3' (https://github.com/daniel-thompson/libopencm3.git) registered for path 'libopencm3'
Submodule 'librfn' (https://github.com/daniel-thompson/librfn.git) registered for path 'librfn'

Cloning into 'C:/cygwin64/home/cmardone/multistomp/libopencm3'...
Cloning into 'C:/cygwin64/home/cmardone/multistomp/librfn'...
error: no such remote ref c19530d6cdbd97b1167365ee95f1edd4db35c978
Fetched in submodule path 'libopencm3', but it did not contain c19530d6cdbd97b1167365ee95f1edd4db35c978. Direct fetching of that commit failed.

**Comment by daniel-thompson** [comment]
You're right. There was an error in the git metadata associated with the 
repo (its working for me but I forgot to push the final changes).

The submodule setup and build is now working. Unforunately I am 
travelling at present so am not able to check on the hardware. However I 
have grabbed the sources directly from my main development machine so 
I'm pretty confident that it should all work when build.

PS There have been some problems reported over the years related to
    USB3 controllers in modern laptops. If you see USB timeouts try
    connecting through a USB2 hub...

**Comment by valpoder** [comment]
Good day Daniel...
thanks for the info...  i installed a virtualmachine (ubuntu)... and repeated the process and now im able clone and compile the sources ... yihey!!!! :)


do you think is possible to recompile your sources for a STM32F103RB @ 8 Mhz ? (any hints on that)

Thank you very much for your help !!

**Comment by daniel-thompson** [comment]
On 07/03/17 22:02, valpoder wrote:
> do you think is possible to recompile your sources for a STM32F103RB @ 8
> Mhz ? (any hints on that)

Are you talking about using a 8MHz crystal or clocking the STM32 at 8MHz 
to save power?

For the former, there's nothing to do. mutlistomp defaults to an 8MHz 
crystal already.

**Comment by valpoder** [comment]
Are you talking about using a 8MHz crystal or clocking the STM32 at 8MHz
to save power?

yes using a 8 Mhz crystal..... 
what about using a STM32F103RB instead of your target   ???  can i use the hex file as it is , or need to modify something else ?

**Comment by daniel-thompson** [comment]
On 08/03/17 16:14, valpoder wrote:
> what about using a STM32F103RB instead of your target ??? can i use the
> hex file as it is , or need to modify something else ?

I'd have to say try it!

However if the part has less SRAM I think it might no work (because the 
stack will end up being created too high up the memory image).

Other than that multistomp is a "normal" opencm3 application so you 
should probably look at the opencm3-examples repository to get a sense 
of what is needed to port between different STM32 boards.


Daniel.

**Comment by valpoder** [comment]
i suspect my issue is due to the bootloader: i was not using the bootloader...i was trying to load the .hex directly with st-link...
