### ISSUE TITLE
Compiled under linux but usb device detected but not correctly

### ISSUE THREAD

**Issue by andrethomas** [daniel-thompson/multistomp#2]
Hi

I've compiled under linux to get the hex file for the bootloader and the bin file for the firmware.

I'ts not detected on windows though... get the following message

![image](https://user-images.githubusercontent.com/470015/34360716-03a1a5d4-ea6c-11e7-839f-5361d855b258.png)

![image](https://user-images.githubusercontent.com/470015/34360725-18d96c02-ea6c-11e7-94c5-857f8f770693.png)

This is on a STM32F103C8T6 - Any ideas?

**Comment by andrethomas** [comment]
Appears to happen when connected to a USB 3.0 port...

Connecting to a USB 2.0 port it shows up in the device manager and in my sound software... but only as a midi out device - something I am missing to get the midi in device part?

Perhaps Windows 10, dunno?

**Comment by daniel-thompson** [comment]
Hi Andre

There have been problems with USB3 in some of my other related USB projects. You could try upgrading to the latest librfn and/or commenting out the running of the "wiggle_task" in main(). Both result in reduced time between calls to the USB service task (although why USB3 dislikes this I have never been able to determine... all the USB3 protocol runs on the extra pins so what the STM32 sees should be the same as with USB2).

Regarding MIDI IN/OUT, the descriptor tables (as you will see in the comments) come directly from the USB standard documentation. I've never tested them in Windows but it really ought to accept these tables.

**Comment by andrethomas** [comment]
Hi

I think the USB3 issue may be hardware specific on the PC side - I know I've had some other devices which did not like the USB3 ports on my PC and then tested with the same result on a notebook.

That aside, I will do what you said and comment out the wiggle_task and report back if there is any difference.

Thanks for the response
